### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Sixela096** [alxscms/homebridge-somfy-protect#1]
Hello,

I have just done the installation, by filling in my somfy protect account, but I can't do anything to control it :/

![image](https://user-images.githubusercontent.com/66483762/100009786-95d24e00-2dcf-11eb-95fd-7b84d5547122.png)
![image](https://user-images.githubusercontent.com/66483762/100009793-9a970200-2dcf-11eb-91e8-fe02849c01e4.png)

When I choose a state, it doesn't work

Thanks for the help

Have a nice day

**Comment by alxscms** [comment]
Hello, 
Do you have any error reported in the logs of homebridge concerning the plugin ?
I did an update yesterday which fixed a few issues, have you tried updating the plugin to this last update ? It might solve your issue. Also what somfy product are you using the plugin for ?

**Comment by Sixela096** [comment]
> Hello,
> Do you have any error reported in the logs of homebridge concerning the plugin ?
> I did an update yesterday which fixed a few issues, have you tried updating the plugin to this last update ? It might solve your issue. Also what somfy product are you using the plugin for ?

Hello,

Thank you, Following your update it works except the home system is it normal?

**Comment by alxscms** [comment]
What do you mean by the home system ?

**Comment by Sixela096** [comment]
![image](https://user-images.githubusercontent.com/66483762/100105401-9b7b7280-2e67-11eb-87b7-400b2beef7de.png)
![image](https://user-images.githubusercontent.com/66483762/100105474-b64de700-2e67-11eb-88cb-9e8c320028fa.png)

**Comment by alxscms** [comment]
Interesting. I just understood that you are using the view accessories from homebridge.
Somfy Protect (as far as I know) doesn't have a mode "Home" state, which is why I specifically removed it from the plugin. If you change the state directly from your Home app on any of your Apple device you will se that you have only 3 modes available : Night, Away and Off.

It seems that homebridge ignores the setting removing the "Home" state. You can just ignore it for now, I will make an update so that if you ever use it, it will just use the "Night" mode instead and not raise any error.

**Comment by Sixela096** [comment]
Hello,

Super thanks a lot for this work !

**Comment by alxscms** [comment]
I'd have no idea no, sorry.
