### ISSUE TITLE
currentState and targetState are invariably the same

### ISSUE THREAD

**Issue by florianlaroye** [alxscms/homebridge-somfy-protect#6]
Hello there,

I’m currently trying to make some home automations but I’m running into an issue where the `currentState` and the `targetState` are not populated properly. Actually, every time the status of the alarm changes, the states are always the same.

For instance, if the status goes from _Night_ to _Disarmed_ the states should be `currentState=2` and the `targetState=3` but the system logs  `currentState=3, targetState=3`.

Would it be possible to have a look at that?

Thanks a lot, this plugin is super great and by updating it I’m sure if can be even better. 👏

**Comment by alxscms** [comment]
Hi,

I'm pretty confused about this issue because the plugin is actually meant to be doing just what you are describing.

Let's reuse your example to describe what is (I think) happening:

**1. Let's say your alarm status is _Night_**
    - `currentState=2`
    - `targetState=2`

**2. You switch the status to _Off_ from the Home app** 
    - `currentState=2`
    - `targetState=3`
Thanks to the two states not being the same, the home app si able to show the label _Disarming..._ informing the user that the state is being changed.
 
**3. Somfy actually responds successfully to the request**
    - `currentState=3`
    - `targetState=3`
The home app is refreshed so that the new state appears to be actually set properly.

Is it not what's happening ? Or is it not what should be happening ?

Thanks for your feedback !
